import mongoose from 'mongoose';
import { Tournament } from '../models/Tournament';

/**
 * Migration script to convert old String-based brackets (JSON string)
 * in the database to the new Mongoose structured bracket subdocuments.
 * 
 * To run:
 * 1. Ensure MONGO_URI is set.
 * 2. Execute via ts-node: npx ts-node server/src/scripts/migrateBrackets.ts
 */
export const migrateBrackets = async () => {
  const connectionString = process.env.MONGO_URI || 'mongodb://localhost:27017/athlix';
  
  if (mongoose.connection.readyState === 0) {
    console.log('Connecting to database...');
    await mongoose.connect(connectionString);
  }

  const tournaments = await Tournament.find({});
  console.log(`Found ${tournaments.length} tournaments to check for migration.`);

  let migratedCount = 0;

  for (const tournament of tournaments) {
    const rawBrackets = (tournament as any).brackets;
    
    // Check if it is stored as a stringified JSON
    if (typeof rawBrackets === 'string' && rawBrackets.trim().startsWith('[')) {
      try {
        const parsed = JSON.parse(rawBrackets);
        
        // Check if the parsed array contains seed structures or rounds
        if (parsed.length > 0 && (parsed[0].fighterId !== undefined || parsed[0].seed !== undefined)) {
          // It was the seeds array generated by AI Seeding
          tournament.brackets = {
            seeds: parsed.map((s: any) => ({
              fighterId: s.fighterId ? new mongoose.Types.ObjectId(s.fighterId) : new mongoose.Types.ObjectId(),
              seed: Number(s.seed || 1),
              rationale: s.rationale || '',
            })),
            rounds: [],
          };
        } else {
          // It was the rounds structure containing matches
          tournament.brackets = {
            seeds: [],
            rounds: parsed,
          };
        }
        
        await tournament.save();
        migratedCount++;
        console.log(`✅ Successfully migrated brackets for tournament: ${tournament._id} (${tournament.title})`);
      } catch (err: any) {
        console.error(`❌ Failed to parse/migrate brackets for tournament ${tournament._id}:`, err.message);
      }
    }
  }

  console.log(`Migration complete. Successfully migrated ${migratedCount} tournaments.`);
  
  if (mongoose.connection.readyState !== 0) {
    await mongoose.disconnect();
    console.log('Disconnected from database.');
  }
};

// Auto-run if script executed directly
if (require.main === module) {
  migrateBrackets()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Fatal Migration Error:', err);
      process.exit(1);
    });
}
